### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by paulgao** [phadej/igbinary#1]
I compile php with igbinary master code, use follow code, echo "Segmentation fault". :-(

plz fix it ASAP. :-)

<?php

$datas = array (
  '123' =>
  array (
    0 => 2450,
    1 => 2184,
    2 => 2227,
    3 => 2228,
    4 => 2293,
    5 => 2369,
    6 => 2421,
    7 => 2426,
    8 => 2447,
    9 => 2478,
    10 => 2477,
    11 => 2486,
    12 => 2489,
    13 => 2490,
    14 => 2491,
    15 => 2494,
    16 => 2493,
    17 => 2492,
    18 => 2422,
    19 => 2446,
    20 => 2431,
    21 => 2275,
    22 => 2274,
    23 => 2235,
    24 => 2518,
    25 => 2520,
    26 => 2528,
    27 => 2533,
    28 => 2544,
    29 => 2545,
    30 => 2546,
    31 => 2596,
    32 => 2597,
    33 => 2598,
    34 => 2630,
    35 => 2652,
    36 => 2676,
    37 => 2682,
    38 => 2292,
    39 => 2683,
    40 => 2648,
    41 => 2700,
    42 => 2606,
    43 => 2706,
    44 => 2713,
    45 => 2714,
    46 => 2736,
    47 => 2229,
    48 => 2742,
    49 => 2758,
    50 => 2445,
    51 => 2785,
    52 => 2814,
    53 => 2819,
    54 => 2820,
    55 => 2480,
    56 => 2821,
    57 => 2838,
    58 => 2898,
    59 => 2901,
    60 => 2902,
    61 => 2941,
    62 => 2943,
    63 => 2965,
    64 => 2973,
    65 => 2872,
    66 => 3018,
    67 => 3019,
    68 => 3020,
    69 => 3021,
    70 => 3022,
    71 => 3023,
    72 => 3035,
    73 => 3042,
    74 => 3046,
    75 => 3045,
    76 => 3056,
    77 => 3082,
    78 => 3087,
    79 => 3089,
    80 => 2481,
    81 => 3096,
    82 => 3097,
    83 => 3098,
    84 => 3100,
    85 => 3102,
    86 => 3116,
    87 => 3142,
    88 => 2883,
    89 => 3154,
    90 => 3158,
    91 => 3129,
    92 => 3168,
    93 => 3173,
    94 => 3189,
    95 => 3058,
    96 => 3231,
    97 => 3232,
    98 => 3233,
    99 => 3251,
    100 => 3252,
    101 => 3253,
    102 => 3276,
    103 => 3277,
    104 => 3338,
    105 => 3346,
    106 => 3241,
    107 => 3364,
    108 => 3366,
    109 => 3375,
    110 => 3378,
    111 => 3377,
    112 => 3386,
    113 => 3394,
    114 => 3405,
    115 => 3415,
    116 => 3417,
    117 => 3418,
    118 => 3424,
    119 => 3434,
    120 => 3435,
    121 => 3439,
    122 => 3442,
    123 => 3230,
    124 => 3379,
    125 => 3421,
    126 => 3370,
    127 => 3229,
    128 => 3412,
    129 => 3325,
    130 => 3227,
    131 => 3451,
    132 => 3452,
    133 => 2882,
    134 => 2942,
    135 => 3454,
    136 => 2684,
    137 => 3101,
    138 => 2566,
    139 => 3458,
    140 => 3459,
    141 => 2625,
    142 => 2850,
    143 => 3373,
    144 => 2482,
    145 => 2476,
    146 => 2371,
    147 => 2904,
    148 => 3446,
    149 => 3527,
    150 => 3294,
    151 => 3191,
    152 => 3333,
    153 => 2989,
    154 => 3078,
    155 => 3390,
    156 => 2905,
    157 => 3099,
    158 => 2823,
    159 => 2826,
    160 => 2896,
    161 => 2936,
    162 => 2934,
    163 => 2162,
    164 => 2906,
    165 => 2294,
    166 => 2449,
    167 => 1940,
    168 => 2799,
    169 => 2394,
    170 => 1979,
    171 => 3469,
    172 => 3471,
    173 => 3447,
    174 => 3363,
    175 => 3404,
    176 => 2903,
    177 => 3477,
    178 => 3478,
    179 => 2813,
    180 => 3485,
    181 => 2935,
    182 => 3403,
    183 => 3497,
    184 => 3501,
    185 => 3504,
    186 => 3365,
    187 => 3511,
    188 => 3512,
    189 => 3510,
    190 => 3286,
    191 => 3516,
    192 => 3517,
    193 => 3519,
    194 => 3522,
    195 => 3523,
    196 => 2940,
    197 => 3413,
    198 => 2931,
    199 => 2759,
    200 => 3529,
    201 => 3591,
    202 => 3608,
    203 => 3607,
    204 => 3616,
    205 => 3619,
    206 => 3620,
    207 => 3621,
    208 => 3623,
    209 => 3624,
    210 => 3631,
    211 => 3414,
    212 => 3376,
    213 => 3685,
    214 => 3433,
    215 => 3432,
    216 => 3334,
    217 => 3419,
    218 => 3702,
    219 => 3509,
    220 => 2451,
    221 => 3147,
    222 => 3228,
    223 => 3717,
    224 => 3725,
    225 => 3731,
    226 => 3748,
    227 => 3741,
    228 => 3763,
    229 => 3754,
    230 => 3834,
    231 => 3788,
    232 => 3789,
    233 => 3793,
    234 => 3794,
    235 => 3799,
    236 => 3802,
    237 => 3806,
    238 => 3808,
    239 => 3810,
    240 => 3811,
    241 => 3923,
    242 => 3924,
    243 => 3820,
    244 => 3823,
    245 => 3824,
    246 => 3825,
    247 => 3826,
    248 => 3795,
    249 => 3832,
    250 => 3833,
    251 => 3835,
    252 => 3838,
    253 => 3861,
    254 => 3867,
    255 => 3868,
    256 => 3871,
    257 => 3874,
    258 => 3875,
    259 => 3883,
    260 => 3884,
    261 => 3885,
    262 => 3886,
    263 => 3887,
    264 => 3888,
    265 => 3894,
    266 => 3893,
    267 => 3895,
    268 => 3896,
    269 => 3897,
    270 => 3898,
    271 => 3899,
    272 => 3900,
    273 => 3901,
    274 => 3902,
    275 => 3922,
    276 => 3906,
    277 => 3908,
    278 => 3911,
    279 => 3916,
    280 => 3917,
    281 => 3918,
    282 => 3925,
    283 => 3926,
    284 => 3927,
    285 => 3928,
    286 => 3932,
    287 => 3933,
    288 => 3934,
    289 => 3935,
    290 => 3936,
    291 => 3938,
    292 => 3948,
    293 => 3949,
    294 => 3950,
    295 => 3951,
    296 => 3952,
    297 => 3953,
    298 => 3954,
    299 => 3955,
    300 => 3957,
    301 => 3958,
    302 => 3960,
    303 => 3975,
    304 => 3981,
    305 => 3987,
    306 => 3988,
    307 => 3989,
    308 => 3993,
    309 => 3994,
    310 => 3996,
    311 => 3997,
    312 => 4000,
    313 => 4001,
    314 => 4002,
    315 => 4004,
    316 => 4009,
    317 => 4010,
    318 => 4016,
    319 => 4024,
    320 => 4026,
    321 => 4027,
    322 => 4028,
    323 => 4030,
    324 => 4031,
    325 => 4032,
    326 => 4035,
    327 => 4036,
    328 => 4041,
    329 => 4043,
    330 => 4046,
    331 => 4048,
    332 => 4049,
    333 => 4050,
    334 => 4051,
    335 => 4052,
    336 => 4053,
    337 => 4054,
    338 => 4055,
    339 => 4068,
    340 => 4069,
    341 => 4070,
    342 => 4071,
    343 => 4072,
    344 => 4073,
    345 => 4074,
    346 => 4075,
    347 => 4076,
    348 => 4077,
    349 => 4078,
    350 => 4079,
    351 => 4080,
    352 => 4081,
    353 => 4082,
    354 => 4083,
    355 => 4084,
    356 => 4085,
    357 => 4086,
    358 => 4096,
    359 => 4098,
    360 => 4099,
    361 => 4126,
    362 => 4131,
    363 => 4132,
    364 => 4137,
    365 => 4185,
    366 => 4241,
    367 => 4242,
    368 => 4251,
    369 => 4258,
    370 => 4259,
    371 => 4260,
    372 => 4261,
    373 => 4559,
    374 => 4563,
    375 => 4571,
    376 => 4574,
    377 => 4575,
    378 => 4576,
    379 => 4589,
    380 => 4590,
    381 => 4591,
    382 => 4593,
    383 => 4594,
    384 => 4600,
    385 => 4602,
    386 => 4608,
    387 => 4610,
    388 => 4625,
    389 => 4630,
    390 => 4631,
  ),
);

$mc = new Memcached;

$mc->addServer('192.168.0.201', 7380);

$mc->setMulti($datas, 3600);

?>

Php.ini for Memcached:

memcached

memcached support => enabled
Version => 2.0.0-dev
libmemcached version => 0.38
Session support  => no
igbinary support => yes
json support => no

Directive => Local Value => Master Value
memcached.compression_factor => 1.3 => 1.3
memcached.compression_threshold => 2048 => 2048
memcached.compression_type => fastlz => fastlz
memcached.serializer => igbinary => igbinary

**Comment by tricky** [comment]
I can't reproduce this using igbinary_serialize, what version of php and exactly which version of igbinary are you using?

Perhaps this Memcached client bug should be reported on somewhere else? :)

**Comment by paulgao** [comment]
I'm using PHP 5.3.2 and the latest code from igbinary's master branch.

I'm not sure whether this problem is related to igbinary or my memcached extension. The above example code did reproduce the problem on my machine, while using igbinary_serialize directly, there's no problem.

**Comment by tricky** [comment]
I'm not at all surprised, that the memcached extension causes a segfault; could you try igbinary_serialize without loading the memcached extension (the later beta version are_much_ safer)?

Could you send a backtrace of the segfault? That would be immensely helpful.

**Comment by paulgao** [comment]
php debug mode:
[root@test]# php igbinary_test.php 

## [Tue May  4 13:36:15 2010]  Script:  'igbinary_test.php'

/root/php-5.3.2/ext/memcached/php_memcached.c(2511) : Block 0x195a9110 status:

## Invalid pointer: ((prev=0x000007c8) != (prev.size=0x2012088302a72012))

## [Tue May  4 13:36:15 2010]  Script:  'igbinary_test.php'

/root/php-5.3.2/ext/memcached/php_memcached.c(1110) : Block 0x195a8098 status:

## Invalid pointer: ((size=0x000008b1) != (next.prev=0x108111208840fa7))

zend_mm_heap corrupted
Segmentation fault

**Comment by paulgao** [comment]
tricky, the backtrace file send to you.

**Comment by tricky** [comment]
This can be closed, the problem was with php-memcached.
