### ISSUE TITLE
php 5.3 support

### ISSUE THREAD

**Issue by atistler** [phadej/igbinary#2]
Any chance that igbinary will work with php 5.3 in the near future?
I get warnings:
igbinary_unserialize_header: version mismatch: 35064129 vs 2

**Comment by tricky** [comment]
It does.

If nothing else, try the latest version from master and try it out. However, bugs exist, can you disclose the string you're unserializing?

**Comment by Glebushka** [comment]
for me this was a misleading error message: I was accidently unserializing value not serialized by igbinary.
