### ISSUE TITLE
Failed test in make test (ubuntu 9.04, zend server ce, php 5.3.3)

### ISSUE THREAD

**Issue by abtris** [phadej/igbinary#3]
## TEST RESULT SUMMARY

Exts skipped    :    0
## Exts tested     :   22

Number of tests :   38                37
Tests skipped   :    1 (  2.6%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    2 (  5.3%) (  5.4%)
Expected fail   :    0 (  0.0%) (  0.0%)
## Tests passed    :   35 ( 92.1%) ( 94.6%)
# Time taken      :    0 seconds
# 
## FAILED TEST SUMMARY

Check for reference serialisation [tests/009.phpt]
Cyclic array test [tests/026.phpt]

**Comment by tricky** [comment]
True, the test fail because a newer var_dump catches reference cycles earlier. The output seems valid anyhow, just the test output fails.

**Comment by phadej** [comment]
This one is fixed now.
