### ISSUE TITLE
Failed tests for PHP 5.4.0RC7-dev

### ISSUE THREAD

**Issue by jjeising** [phadej/igbinary#7]
Two tests fail for PHP 5.4.0RC7-dev.

FAIL Recursive objects [ext/igbinary/tests/024.phpt]: No ouput instead of expected.

FAIL Unserialize backwards compatible with v1. [ext/igbinary/tests/unserialize_v1_compatible.phpt]: 

```
Differing unserialized: object
Expected:
object(stdClass)#0 (4) {
  ["0"]=>
  int(1)
  ["1"]=>
  int(2)
  ["2"]=>
  int(3)
  ["3"]=>
  int(4)
}

Actual:
object(stdClass)#0 (4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
```

**Comment by Esysteme** [comment]
it's work with php 5.5?

**Comment by jjeising** [comment]
These work with PHP 5.6.1, while 46 fails (Correctly unserialize scalar refs). Closing this for now.
